config/routes.rb
Rails.application.routes.draw do
  root to: 'clients#index'

  get '/clients/:id' => 'clients#show', as: :client

  get 'clients/new'

  get 'clients/create'

  get 'clients/edit'

  get 'clients/update'

  get 'clients/delete'

  get 'clients/destroy'

  get '/products' => 'products#index'

  get '/products/:id' => 'products#show', as: :product

  get 'products/new'

  get 'products/create'

  get 'products/edit'

  get 'products/update'

  get 'products/delete'

  get 'products/destroy'

	resources :products
	resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
has_many :parts
has_many :products, through: :parts
end

app/models/part.rb
class Part < ActiveRecord::Base
belongs_to :client
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :parts
has_many :clients, through: :parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
	@clients = Client.all
  end

  def show
	@client = Client.find(params[:id])
	@products = @client.products
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
	@products = Product.all
  end

  def show
	@product = Product.find(params[:id])
	@clients = @product.clients
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/delete.html.erb
<h1>Clients#delete</h1>
<p>Find me in app/views/clients/delete.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Clients#edit</h1>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<br>
<h1>Autorzy dzieł sztuki</h1>
<div class="main client-index">
<div class="container">
<div class="row">
<% @clients.each do |client| %>
<div class="client col-xs-2">
<%= image_tag client.image %>
<h3><%= client.name %>
<%= link_to "Więcej", client_path(client) %>
</div>
<% end %>
</div>
</div>
</div>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<div class="main client-show">
<div class="container">
<div class="client">
<%= image_tag @client.image %>
<div class="info">
<h3 class="client-name"><%= @client.name %></h3>
<p class="client-bio"><%= @client.bio %></p>
</div>
</div>

<h2>Produkty</h2>
<% @products.each do |product| %>
<div class="product">
<%= image_tag product.image %>
<h3 class="product-title"><%= product.title %></h3>
<p class="product=release-year"><%= product.release_year %></p>
<p class="product-description"><%= product.description %></p>
</div>
<% end %>
</div>
</div>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Probna</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
        
     <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>

  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<div class="container">
	
	<h3>Opis produktów będących celem prezentacji</h3>
	
</div>

<div class="main">
	<div class="container">
	<h2>Popularne produkty</h2>

	<% @products.each do |product| %>
		<div class="product">
			<%= image_tag product.image %>
			<h3><%= product.title %></h3>
			<p><%= product.release_year %></p>
			<p><%= product.description %></p>
			<%= link_to "Więcej", product_path(product) %>
		</div>
		<% end %>

	</div>
</div>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<div class="main product-show">
<div class="container">
<div class="movie">
<div class="info"
<%= image_tag @product.image %>
<h3 class="product-title"><%= @product.title %></h3>
<p class="product-release-year"><%= @product.release_year %></p>
<p class="product-description"><%= @product.description %></p>
</div>
</div>

<h2>Klienci</h2>
<% @clients.each do |client| %>
<div class="client">
<%= image_tag client.image %>
<h3 class="client-name"><%= client.name %></h3>
<p class="client-bio"><%= client.bio %></p>
</div>
<% end %>
</div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>